"""resto del modelo de dominio

Revision ID: 7f8c9d354e09
Revises: b1c4e9f27a30
Create Date: 2026-08-05 21:54:35.718647

Dos ajustes a mano sobre lo que generó el autogenerate:

1. Se han eliminado tres `op.drop_constraint` sobre las CHECK `tipofuente`, `formatofuente`
   (tabla `fuente`) y `estadopipeline` (tabla `documento`). Es el mismo falso positivo que ya
   apareció en la migración 0243743f134a: alembic no reconstruye las CHECK que genera
   `Enum(native_enum=False, create_constraint=True)` al reflejar el esquema, así que las ve
   como sobrantes en cada autogenerate. Aplicarlas habría borrado en silencio la validación de
   vocabulario en base de datos. **Repasar esto en toda migración futura.**

2. Se añade a mano el trigger de inmutabilidad de `version_norma` (ver abajo).

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# El histórico de versiones de norma es inmutable (CLAUDE.md sección 5). Se hace cumplir en la
# base de datos y no solo en el ORM: la inmutabilidad es parte del valor del proyecto — un
# archivo de lo que se publicó que se pueda editar después no sirve como archivo — y un
# control que dependa de que nadie escriba un UPDATE a mano no es un control. Corregir un
# error significa insertar una versión nueva que lo diga, nunca reescribir la anterior.
_TRIGGER_INMUTABILIDAD = """
CREATE OR REPLACE FUNCTION version_norma_es_inmutable()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'version_norma es inmutable: no se permite % (CLAUDE.md seccion 5)',
        TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_version_norma_inmutable
BEFORE UPDATE OR DELETE ON version_norma
FOR EACH ROW EXECUTE FUNCTION version_norma_es_inmutable();
"""

_QUITAR_TRIGGER_INMUTABILIDAD = """
DROP TRIGGER IF EXISTS trg_version_norma_inmutable ON version_norma;
DROP FUNCTION IF EXISTS version_norma_es_inmutable();
"""

# revision identifiers, used by Alembic.
revision: str = "7f8c9d354e09"
down_revision: str | Sequence[str] | None = "b1c4e9f27a30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suscriptor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=False),
        sa.Column("webhook_url", sa.String(length=1000), nullable=True),
        sa.Column("ccaa_interes", sa.JSON(), nullable=True),
        sa.Column("token_baja_opaco", sa.String(length=64), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_hash"),
        sa.UniqueConstraint("token_baja_opaco"),
    )
    op.create_table(
        "norma",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("documento_id", sa.Integer(), nullable=False),
        sa.Column("identificador_oficial", sa.String(length=200), nullable=False),
        sa.Column("titulo", sa.Text(), nullable=False),
        sa.Column("url_texto", sa.String(length=1000), nullable=True),
        sa.Column(
            "rango",
            sa.Enum(
                "ley",
                "decreto",
                "orden",
                "instruccion",
                "resolucion",
                "proposicion",
                name="rangonorma",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("organo_emisor", sa.String(length=300), nullable=True),
        sa.Column(
            "ambito",
            sa.Enum(
                "sanitario",
                "educativo",
                "laboral",
                "documental",
                "deportivo",
                "general",
                name="ambitonorma",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["documento_id"], ["documento.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("documento_id", "identificador_oficial", name="uq_norma_doc_ident"),
    )
    op.create_index(op.f("ix_norma_ambito"), "norma", ["ambito"], unique=False)
    op.create_index(op.f("ix_norma_documento_id"), "norma", ["documento_id"], unique=False)
    op.create_index(
        op.f("ix_norma_identificador_oficial"), "norma", ["identificador_oficial"], unique=False
    )
    op.create_table(
        "deteccion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("norma_id", sa.Integer(), nullable=False),
        sa.Column(
            "extraccion_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "clasificacion",
            sa.Enum(
                "avance",
                "retroceso",
                "neutro",
                "indeterminado",
                name="clasificacion",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "origen",
            sa.Enum(
                "derivado_diff",
                "heuristica",
                name="origenclasificacion",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("regla_aplicada", sa.String(length=100), nullable=True),
        sa.Column("severidad", sa.Integer(), nullable=False),
        sa.Column("confianza", sa.Float(), nullable=False),
        sa.Column("revisada", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("confianza >= 0 AND confianza <= 1", name="ck_deteccion_confianza"),
        sa.CheckConstraint("severidad >= 1 AND severidad <= 5", name="ck_deteccion_severidad"),
        sa.ForeignKeyConstraint(["norma_id"], ["norma.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deteccion_clasificacion"), "deteccion", ["clasificacion"], unique=False
    )
    op.create_index(op.f("ix_deteccion_norma_id"), "deteccion", ["norma_id"], unique=False)
    op.create_index(
        op.f("ix_deteccion_regla_aplicada"), "deteccion", ["regla_aplicada"], unique=False
    )
    op.create_index(op.f("ix_deteccion_revisada"), "deteccion", ["revisada"], unique=False)
    op.create_table(
        "version_norma",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("norma_id", sa.Integer(), nullable=False),
        sa.Column("version_anterior_id", sa.Integer(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("articulo", sa.String(length=300), nullable=True),
        sa.Column("texto_anterior", sa.Text(), nullable=True),
        sa.Column("texto_nuevo", sa.Text(), nullable=True),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["norma_id"], ["norma.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["version_anterior_id"], ["version_norma.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_version_norma_norma_id"), "version_norma", ["norma_id"], unique=False)
    op.create_index(
        op.f("ix_version_norma_version_anterior_id"),
        "version_norma",
        ["version_anterior_id"],
        unique=False,
    )
    op.create_table(
        "alerta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deteccion_id", sa.Integer(), nullable=False),
        sa.Column(
            "emitida_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["deteccion_id"], ["deteccion.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deteccion_id"),
    )
    op.create_table(
        "cola_revision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deteccion_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "pendiente",
                "aprobada",
                "descartada",
                name="estadorevision",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="pendiente",
            nullable=False,
        ),
        sa.Column(
            "creada_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resuelta_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nota_revision", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["deteccion_id"], ["deteccion.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deteccion_id"),
    )
    op.create_index(op.f("ix_cola_revision_estado"), "cola_revision", ["estado"], unique=False)
    # ### end Alembic commands ###

    # Añadido a mano: inmutabilidad de version_norma a nivel de base de datos.
    op.execute(_TRIGGER_INMUTABILIDAD)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(_QUITAR_TRIGGER_INMUTABILIDAD)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cola_revision_estado"), table_name="cola_revision")
    op.drop_table("cola_revision")
    op.drop_table("alerta")
    op.drop_index(op.f("ix_version_norma_version_anterior_id"), table_name="version_norma")
    op.drop_index(op.f("ix_version_norma_norma_id"), table_name="version_norma")
    op.drop_table("version_norma")
    op.drop_index(op.f("ix_deteccion_revisada"), table_name="deteccion")
    op.drop_index(op.f("ix_deteccion_regla_aplicada"), table_name="deteccion")
    op.drop_index(op.f("ix_deteccion_norma_id"), table_name="deteccion")
    op.drop_index(op.f("ix_deteccion_clasificacion"), table_name="deteccion")
    op.drop_table("deteccion")
    op.drop_index(op.f("ix_norma_identificador_oficial"), table_name="norma")
    op.drop_index(op.f("ix_norma_documento_id"), table_name="norma")
    op.drop_index(op.f("ix_norma_ambito"), table_name="norma")
    op.drop_table("norma")
    op.drop_table("suscriptor")
    # ### end Alembic commands ###
